# Generated by Django 3.1.5 on 2021-02-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='List_image_url',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='List_start_price',
            field=models.FloatField(default=0),
        ),
    ]
