# Generated by Django 3.1.5 on 2021-02-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210224_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist_items',
            field=models.ManyToManyField(blank=True, related_name='whishlist', to='auctions.Listings'),
        ),
    ]
