# Generated by Django 3.1.5 on 2021-02-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_wishlist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishlist_items',
        ),
    ]
