# Generated by Django 3.1.5 on 2021-02-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_user_wishlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='List_category',
            field=models.CharField(default='No Category', max_length=32),
        ),
    ]
