# Generated by Django 3.1.5 on 2021-02-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
