# Generated by Django 3.1.5 on 2021-03-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210226_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='listings',
            name='List_category',
            field=models.ForeignKey(default='No Category', on_delete=django.db.models.deletion.CASCADE, to='auctions.category_list'),
        ),
    ]
