# Generated by Django 3.1.5 on 2021-03-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_won',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='List_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_user', to='auctions.user'),
            preserve_default=False,
        ),
    ]
